ruoyi:
  name: WoodPecker
  version: 3.8.3
  copyrightYear: 2022
  demoEnabled: false
  profile: /Users/le/Documents/agileTCporject/log
  addressEnabled: false
  captchaType: math

server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    uri-encoding: UTF-8
    accept-count: 1000
    threads:
      max: 800
      min-spare: 100

logging:
  level:
    com.kele: info
    org.springframework: warn

user:
  password:
    maxRetryCount: 5
    lockTime: 10

spring:
  messages:
    basename: i18n/messages
  profiles:
    active: druid
  servlet:
    multipart:
      max-file-size:  10MB
      max-request-size:  20MB
  devtools:
    restart:
      enabled: true
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    timeout: 10s
    lettuce:
      pool:
        min-idle: 0
        max-idle: 8
        max-active: 8
        max-wait: -1ms
  kafka:
    bootstrap-servers: 192.168.0.124:9092
    consumer:
      group-id: test
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      missing-topics-fatal: false


token:
  header: Authorization
  secret: abcdefghijklmnopqrstuvwxyz
  expireTime: 10080

mybatis:

  typeAliasesPackage: com.kele.woodpecker.project.**.domain
  mapperLocations: classpath*:mybatis/**/*Mapper.xml
  configLocation: classpath:mybatis/mybatis-config.xml

pagehelper:
  helperDialect: mysql
  supportMethodsArguments: true
  params: count=countSql


xss:
  enabled: true
  excludes: /system/notice
  urlPatterns: /system/*,/monitor/*,/tool/*

gen:
  author: ruoyi
  packageName: com.kele.woodpecker.project.system
  autoRemovePre: false
  tablePrefix: sys_


